<!DOCTYPE HTML>
<html>

    <head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
	<meta name="description" content="By way of introduction, I am Vasu Dev Puri and am living in United Arab Emirates, Dubai. I am currently working with the Valuations and Modelling team at PwC Deals through which I’ve worked on several fair value, business restructuring / turnaround , asset optimization, business strategy, purchase price allocations, synthetic credit ratings and business model review engagements. In addition, I have also built benchmarking and interactive dashboards running on live data from Bloomberg / Capital IQ, using Data Analytic tools such as Power BI and Power Pivot.">
	<meta name="author" content="Vasu Dev Puri">
	<meta name="generator" content="Hugo 0.74.3" />
	<title>Climate Change Analysis - Is it really a hoax? &middot; Portfolio website for Vasu Puri</title>
	<!-- Stylesheets -->
	
	<link rel="stylesheet" href="https://vasudevpuri.netlify.app/css/main.css"/>
	
	

	

	<!-- Custom Fonts -->
	<link href="https://vasudevpuri.netlify.app/css/font-awesome.min.css" rel="stylesheet" type="text/css">

	
	<link rel="shortcut icon" type="image/x-icon" href="https://vasudevpuri.netlify.app/favicon.ico">
	<link rel="icon" type="image/x-icon" href="https://vasudevpuri.netlify.app/favicon.ico">
	

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="js/ie/html5shiv.js"></script>
	<script src="js/ie/html5shiv.jsrespond.min.js"></script>
	<![endif]-->
</head>

    <body>

    <!-- Wrapper -->
        <div id="wrapper">

            <!-- Header -->
    <header id="header" class="alt">
        <a href="https://vasudevpuri.netlify.app/" class="logo"><strong>Vasu Dev Puri</strong> <span></span></a>
        <nav>
            <a href="#menu"></a>
        </nav>
    </header>

<!-- Menu -->
    <nav id="menu">
        <ul class="links">
            
                <li><a href="https://vasudevpuri.netlify.app/">Home</a></li>
            

        </ul>
        <ul class="actions vertical">
            
            
        </ul>
    </nav>

        <!-- Main -->
            <div id="main" class="alt">

                
                    <section id="one">
                        <div class="inner">
                            <header class="major">
                                <h1>Climate Change Analysis - Is it really a hoax?</h1>
                            </header>
                            
                            
<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />


<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<p>In the first section of this report we will be studying climate change by looking at temperature anomalies recorded since 1880, specifically the deviations from the expected temperature. The raw data is the <em>Combined Land-Surface Air and Sea-Surface Water Temperature Anomalies</em> in the Northern Hemisphere at <a href="https://data.giss.nasa.gov/gistemp">NASA’s Goddard Institute for Space Studies</a>. The <a href="https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.txt">tabular data of temperature anomalies can be found here.</a></p>
<pre class="r"><code>weather &lt;- 
  read_csv(&quot;https://data.giss.nasa.gov/gistemp/tabledata_v3/NH.Ts+dSST.csv&quot;, 
           skip = 1, 
           na = &quot;***&quot;)</code></pre>
<pre class="r"><code>#remove unnecessary columns from the original data frame
remove_cols &lt;- weather %&gt;%
  select(1:13)

tidyweather &lt;- remove_cols %&gt;%
  pivot_longer(cols = 2:13, names_to = &quot;Month&quot;, values_to = &quot;delta&quot;)</code></pre>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>After tidying the data, we plot it in a time-series scatter plot below.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         month = month(date, label=TRUE),
         year = year(date))

ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point(size = 0.5)+
  geom_smooth(color=&quot;red&quot;) +
  labs (
    title = &quot;The planet is getting warmer!&quot;, subtitle = &quot;Weather anomalies since 1880&quot;, x = &quot;Year&quot;, y = &quot;Temperature Deviation&quot;, caption = &quot;Source: NASA&#39;s Goddard Institute for Space Studies&quot;
  ) + 
  theme_minimal()</code></pre>
<p><img src="/projects/project3/index_files/figure-html/scatter_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>By further analysing the data below we can observe that the effect of increasing temperature is more pronounced in some months. In fact, evident from both the follwing scatter plots and summary statistics, we see that October has the highest mean delta, indicating that it has a more pronounced overall increase in temperature compared to other months. Months at the start of the year (Jan, Feb, Mar) also have larger variation in delta compared to other months.</p>
<pre class="r"><code>#faceting data per month 
ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point(size = 0.3)+
  geom_smooth(color = &quot;red&quot;) +
  theme_bw() +
  facet_wrap(~month) +
  labs (title = &quot;October has become the month with the most unexpected weather&quot;, subtitle = &quot;Weather Anomalies since 1880 by month&quot;, x = &quot;Year&quot;, y = &quot;Temperature Deviation&quot;, caption = &quot;Source: NASA&#39;s Goddard Institute for Space Studies&quot;) </code></pre>
<p><img src="/projects/project3/index_files/figure-html/facet_wrap-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>insights_avgdelta &lt;- tidyweather %&gt;%
  group_by(Month) %&gt;%
  #summary statistics for our deltas 
  summarize(mean = mean(delta, 
  #ignore missing values 
  na.rm = TRUE)) 

#formatting table 
library(kableExtra)
insights_avgdelta %&gt;%
  arrange(desc(mean)) %&gt;%
  kbl(caption = &quot;Mean Temperature Deviation per month&quot;) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:facet_wrap)Mean Temperature Deviation per month
</caption>
<thead>
<tr>
<th style="text-align:left;">
Month
</th>
<th style="text-align:right;">
mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Oct
</td>
<td style="text-align:right;">
0.106
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar
</td>
<td style="text-align:right;">
0.098
</td>
</tr>
<tr>
<td style="text-align:left;">
Nov
</td>
<td style="text-align:right;">
0.083
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb
</td>
<td style="text-align:right;">
0.076
</td>
</tr>
<tr>
<td style="text-align:left;">
Sep
</td>
<td style="text-align:right;">
0.065
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr
</td>
<td style="text-align:right;">
0.060
</td>
</tr>
<tr>
<td style="text-align:left;">
Jul
</td>
<td style="text-align:right;">
0.051
</td>
</tr>
<tr>
<td style="text-align:left;">
Jun
</td>
<td style="text-align:right;">
0.046
</td>
</tr>
<tr>
<td style="text-align:left;">
May
</td>
<td style="text-align:right;">
0.042
</td>
</tr>
<tr>
<td style="text-align:left;">
Jan
</td>
<td style="text-align:right;">
0.040
</td>
</tr>
<tr>
<td style="text-align:left;">
Aug
</td>
<td style="text-align:right;">
0.038
</td>
</tr>
<tr>
<td style="text-align:left;">
Dec
</td>
<td style="text-align:right;">
0.023
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>insights_sddelta &lt;- tidyweather %&gt;%
  group_by(Month) %&gt;%
  #summary statistics for our deltas 
  summarize(&quot;sd&quot; = sd(delta, na.rm = TRUE)) 

#formatting table
library(kableExtra)
insights_sddelta %&gt;%
  arrange(desc(sd)) %&gt;%
  kbl(caption = &quot;Standard Deviation of Temperature Anomalies per month&quot;) %&gt;%
  kable_styling()</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:stdev_deltas)Standard Deviation of Temperature Anomalies per month
</caption>
<thead>
<tr>
<th style="text-align:left;">
Month
</th>
<th style="text-align:right;">
sd
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Jan
</td>
<td style="text-align:right;">
0.533
</td>
</tr>
<tr>
<td style="text-align:left;">
Feb
</td>
<td style="text-align:right;">
0.533
</td>
</tr>
<tr>
<td style="text-align:left;">
Mar
</td>
<td style="text-align:right;">
0.508
</td>
</tr>
<tr>
<td style="text-align:left;">
Dec
</td>
<td style="text-align:right;">
0.473
</td>
</tr>
<tr>
<td style="text-align:left;">
Apr
</td>
<td style="text-align:right;">
0.448
</td>
</tr>
<tr>
<td style="text-align:left;">
Nov
</td>
<td style="text-align:right;">
0.442
</td>
</tr>
<tr>
<td style="text-align:left;">
Oct
</td>
<td style="text-align:right;">
0.401
</td>
</tr>
<tr>
<td style="text-align:left;">
May
</td>
<td style="text-align:right;">
0.385
</td>
</tr>
<tr>
<td style="text-align:left;">
Jun
</td>
<td style="text-align:right;">
0.380
</td>
</tr>
<tr>
<td style="text-align:left;">
Aug
</td>
<td style="text-align:right;">
0.364
</td>
</tr>
<tr>
<td style="text-align:left;">
Sep
</td>
<td style="text-align:right;">
0.361
</td>
</tr>
<tr>
<td style="text-align:left;">
Jul
</td>
<td style="text-align:right;">
0.355
</td>
</tr>
</tbody>
</table>
<p>It is sometimes useful to group data into different time periods to study historical data (eg. 1970s, 1980s), which we do below after removing data before 1800. Note that NASA calculates a temperature anomaly, as difference from the base period of 1951-1980.</p>
<pre class="r"><code>#The code below creates a new data frame called `comparison` that groups data 
#in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010 and 2011-present. 

comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     #remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot; ))
  
  comparison </code></pre>
<pre><code>## # A tibble: 1,668 x 7
##     Year Month delta date       month  year interval 
##    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;date&gt;     &lt;ord&gt; &lt;dbl&gt; &lt;chr&gt;    
##  1  1881 Jan   -0.19 1881-01-01 Jan    1881 1881-1920
##  2  1881 Feb   -0.25 1881-02-01 Feb    1881 1881-1920
##  3  1881 Mar    0.02 1881-03-01 Mar    1881 1881-1920
##  4  1881 Apr   -0.02 1881-04-01 Apr    1881 1881-1920
##  5  1881 May   -0.06 1881-05-01 May    1881 1881-1920
##  6  1881 Jun   -0.36 1881-06-01 Jun    1881 1881-1920
##  7  1881 Jul   -0.06 1881-07-01 Jul    1881 1881-1920
##  8  1881 Aug   -0.03 1881-08-01 Aug    1881 1881-1920
##  9  1881 Sep   -0.23 1881-09-01 Sep    1881 1881-1920
## 10  1881 Oct   -0.4  1881-10-01 Oct    1881 1881-1920
## # ... with 1,658 more rows</code></pre>
<pre class="r"><code>  comparison %&gt;%
  rename(&quot;Delta&quot; = &quot;delta&quot; , &#39;Full Date&#39; = &#39;date&#39;,
         &#39;Months&#39; = &#39;month&#39;,&#39;Years&#39; = &#39;year&#39; ,
         &#39;Interval&#39; = &#39;interval&#39;)</code></pre>
<pre><code>## # A tibble: 1,668 x 7
##     Year Month Delta `Full Date` Months Years Interval 
##    &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;date&gt;      &lt;ord&gt;  &lt;dbl&gt; &lt;chr&gt;    
##  1  1881 Jan   -0.19 1881-01-01  Jan     1881 1881-1920
##  2  1881 Feb   -0.25 1881-02-01  Feb     1881 1881-1920
##  3  1881 Mar    0.02 1881-03-01  Mar     1881 1881-1920
##  4  1881 Apr   -0.02 1881-04-01  Apr     1881 1881-1920
##  5  1881 May   -0.06 1881-05-01  May     1881 1881-1920
##  6  1881 Jun   -0.36 1881-06-01  Jun     1881 1881-1920
##  7  1881 Jul   -0.06 1881-07-01  Jul     1881 1881-1920
##  8  1881 Aug   -0.03 1881-08-01  Aug     1881 1881-1920
##  9  1881 Sep   -0.23 1881-09-01  Sep     1881 1881-1920
## 10  1881 Oct   -0.4  1881-10-01  Oct     1881 1881-1920
## # ... with 1,658 more rows</code></pre>
<p>Below we create a density plot to study the distribution of monthly deviations (<code>delta</code>), grouped by the different time periods we are interested in.</p>
<pre class="r"><code>comparison%&gt;%
group_by(interval)%&gt;%
ggplot(aes(x=delta, fill=interval)) +
  geom_density(alpha=0.2) +   
  theme_bw() +               
  labs (title = &quot;Things are getting hotter!&quot;, subtitle = &quot;Distribution of temperature deviations for each time interval&quot;, x = &quot;Temperature Deviations&quot;, caption =&quot;Source: NASA&#39;s Goddard Institute for Space Studies&quot;) </code></pre>
<p><img src="/projects/project3/index_files/figure-html/density_plot-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>So far, we have been working with monthly anomalies. However, below we proceed to inspect the average annual anomalies and create a scatter plot to display the results.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # creating summaries for mean delta 
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(annual_average_delta = mean(delta, na.rm=TRUE)) 

#plotting the data:
ggplot(average_annual_anomaly, aes(x=Year, y= annual_average_delta))+
  geom_point()+
  
  #Fit the best fit line, using LOESS method
  geom_smooth() +
  
  #change to theme_bw() to have white background + black frame around plot
  theme_bw() +
  labs (title = &quot;Does the weather get more unpredictable as the years go by?&quot;, subtitle = &quot;Average temperature deviation per year&quot;, y = &quot;Average Annual Temperature Deviation&quot;,  caption =&quot;Source: NASA&#39;s Goddard Institute for Space Studies&quot;)                         </code></pre>
<p><img src="/projects/project3/index_files/figure-html/averaging-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="confidence-interval-for-temperature-anomalies" class="section level2">
<h2>Confidence Interval for Temperature Anomalies</h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their website</a> that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast amount of heat to warm all the oceans, atmosphere, and land by that much. In the past, a one- to two-degree drop was all it took to plunge the Earth into the Little Ice Age.</p>
</blockquote>
<p>Below we construct a confidence interval for the average annual delta since 2011 using two different methodologies.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
  # choose the interval 2011-present
  filter(interval==&quot;2011-present&quot;) %&gt;% 
  summarise(mean=mean(delta,na.rm=TRUE),sd=sd(delta,na.rm=TRUE), count=n(),se=sd/sqrt(count)) %&gt;%
  summarise(lower_ci = mean-1.96*se, upper_ci = mean+1.96*se) %&gt;%
  rename(&quot;Lower Boundary&quot; = &#39;lower_ci&#39;, &quot;Upper Boundary&quot; = &#39;upper_ci&#39; ) %&gt;%
kbl(caption = &#39;Confidence Interval for the annual delta since 2011&#39;)%&gt;%
  kable_styling() 

formula_ci </code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:calculate_CI_using_formula)Confidence Interval for the annual delta since 2011
</caption>
<thead>
<tr>
<th style="text-align:right;">
Lower Boundary
</th>
<th style="text-align:right;">
Upper Boundary
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.916
</td>
<td style="text-align:right;">
1.01
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>bootstrap_delta &lt;- comparison %&gt;% 
  filter(interval==&quot;2011-present&quot;) %&gt;% 
  specify(response=delta) %&gt;%
  generate(reps =1000, type =&quot;bootstrap&quot;) %&gt;%
  calculate(stat =&quot;mean&quot;)
infer_ci &lt;- bootstrap_delta %&gt;% 
  get_confidence_interval(level=0.95,type=&quot;percentile&quot;) %&gt;%
  rename(&quot;Lower Boundary&quot; = &#39;lower_ci&#39;, &quot;Upper Boundary&quot; = &#39;upper_ci&#39; ) %&gt;%
  kbl(caption = &#39;Confidence Interval for the annual delta since 2011&#39;)%&gt;%
  kable_styling()

infer_ci</code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
(#tab:calculate_CI_using_bootstrap)Confidence Interval for the annual delta since 2011
</caption>
<thead>
<tr>
<th style="text-align:right;">
Lower Boundary
</th>
<th style="text-align:right;">
Upper Boundary
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.92
</td>
<td style="text-align:right;">
1.02
</td>
</tr>
</tbody>
</table>
<p>In the first code block, we manually calculate the confidence interval using the SE, count and mean. Since we are assuming normal distribution, we use the critical Z value for 95%, which is 1.96. In the second code block, we have bootstrapped the data by sampling 1000 times and calculated the mean from all these sampled sets. We then obtain a confidence interval for the mean delta. As seen from above, the two results are very similar. We are confident that in 95% of the time, the average delta will be in between 0.916 and 1.02.</p>
</div>
</div>

                        </div>
                    </section>
            <!-- Disqus Inject -->
                
            </div>
            
        <!-- Footer -->
            
                <!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="icons">
                
                    <li><a href="https://github.com/Vasudevpuri" class="icon alt fa-github" target="_blank"><span class="label">GitHub</span></a></li>
                
                    <li><a href="https://www.linkedin.com/in/vasudevpuri" class="icon alt fa-linkedin" target="_blank"><span class="label">LinkedIn</span></a></li>
                
            </ul>
            <ul class="copyright">
                <li>&copy; Company Name</li>
                
            </ul>
        </div>
    </footer>

            
        </div>

    <!-- Scripts -->
        <!-- Scripts -->
    <!-- jQuery -->
    <script src="https://vasudevpuri.netlify.app/js/jquery.min.js"></script>
    <script src="https://vasudevpuri.netlify.app/js/jquery.scrolly.min.js"></script>
    <script src="https://vasudevpuri.netlify.app/js/jquery.scrollex.min.js"></script>
    <script src="https://vasudevpuri.netlify.app/js/skel.min.js"></script>
    <script src="https://vasudevpuri.netlify.app/js/util.js"></script>

    

    <!-- Main JS -->
    <script src="https://vasudevpuri.netlify.app/js/main.js"></script>

    

    

    </body>
</html>
